#!/bin/bash
#
# Init file for Adaptor VMware 
#
# chkconfig: 2345 55 25
# description: Adaptor VMware 
#

# source function library
# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
runlevel=$(set -- $(runlevel); eval "echo \$$#" )
prog=adaptor-vmware

start()
{
	if [ -f /var/run/adaptor-vmware.pid ]; then
		echo "Already running"
		exit 1
	fi
	echo -n $"Starting $prog: "
	/usr/bin/padrino start --chdir=/opt/6fusion/adaptor-vmware --pid=/var/run/adaptor-vmware.pid > /var/log/adaptor-vmware 2>&1 &
	RETVAL=$?
	[ $RETVAL -eq 0 ] && success || failure
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	/usr/bin/padrino stop --chdir=/opt/6fusion/adaptor-vmware --pid=/var/run/adaptor-vmware.pid
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		restart
		;;
	condrestart)
		restart
		;;
	status)
        	status -p /var/run/adaptor-vmware.pid adaptor-vmware
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL