#!/bin/bash
#
# Init file for Adaptor VMware 
#
# chkconfig: 2345 55 25
# description: Adaptor VMware 
#

# source function library
# source function library
. /etc/rc.d/init.d/functions

RETVAL=0

runlevel=$(set -- $(runlevel); eval "echo \$$#" )

start()
{
	echo -n $"Starting $prog: "
	if [ "`pidof -x god`" = "" ]
	then
		/usr/local/bin/god -c /etc/god.conf
	fi
	/usr/local/bin/god start all
	echo
}

stop()
{
	echo -n $"Stopping $prog: "
    	/usr/local/bin/god stop all
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		restart
		;;
	condrestart)
		restart
		;;
	status)
        	/usr/local/bin/god status all
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL