user_id:
  automationtestuser:
    account_id: <%= Account.find_by_accountname("automationtestuser").id %>
  automationtestuser2:
    account_id: <%= Account.find_by_accountname("automationtestuser2").id %>
  automationtestuser3:
    account_id: <%= Account.find_by_accountname("automationtestuser3").id %>
  automationtestuser4:
    account_id: <%= Account.find_by_accountname("automationtestuser4").id %>
  automationtestuser5:
    account_id: <%= Account.find_by_accountname("automationtestuser5").id %>
  UC6Admin:
    account_id: 1

roles:
  UCVendors:
    login: automationtestuser2@6fusion.com
    password: 7u8i&U*I
  Solution_Providers_And_UCVendors:
    login: automationtestuser3@6fusion.com
    password: 7u8i&U*I
  Admin:
    login: UC6admin@6fusion.com
    password: 1q2w!Q@W
  Solution_Providers:
    login: automationtestuser4@6fusion.com
    password: 7u8i&U*I
  Profiler:
    login: automationtestuser5@6fusion.com
    password: 7u8i&U*I

canned_data:
     auth_token: <%= User.find_by_email('automationtestuser@6fusion.com').authentication_token %>
     CRM_URL: http://localhost:5000
     Disk_Name: <%= Medium.find_by_description('Full_Test_OVF').media_files.find_by_filename('FreeNAS72-disk1.vmdk').id %>
     Engine_Room_Test_NIC_Field_Name: network-name-<%= Medium.find_by_description('Public Media Template for Automation').network_interfaces.first.id %>
     iNode: Engine Room 1.0 Automation iNode
     iNode_ID: <%= DataCenter.find_by_description('Engine Room 1.0 Automation iNode').id %>
     ISO: "DSLinux"
     Meter: Engine Room 1.0 Automation iNode Meter
     Media_ID_1: <%= Medium.find_by_internalpath('/medium/for/automation/1').id %>
     Media_ID_2: <%= Medium.find_by_internalpath('/medium/for/automation/2').id %>
     Network_Mapping: <%= DataCenter.find_by_description('Engine Room 1.0 Automation iNode').old_engine_room_networks.public.first.id %>
     NIC: VINET02
     NIC_Field_Name: network-name-<%= Medium.find_by_description('Full_Test_OVF').network_interfaces.first.id %>
     NIC_ID_1: <%= Medium.find_by_description('Full_Test_OVF').network_interfaces.first.id %>
     auth_token: <%= User.find_by_email('automationtestuser@6fusion.com').authentication_token %>
     admin_auth_token: <%= User.find_by_email('uc6admin@6fusion.com').authentication_token %>
     Profiler_Name: "Automation_Test_Profiler - DO NOT DELETE"
     Private_iNode: ""
     Public_iNode: "Engine Room 1.0 Development iNode"
     Template: Full_Test_OVF
     Template_2: <%= Medium.find_by_internalpath('/medium/for/automation/1').name %>
     Xen_Engine_Room: "Engine Room for Xen Development iNode"

engine_room_2:
     Xen_iNode: "gin xen 6.0"
     Xen_Network_Management_Server_Interfaces: ""
     VMWare_iNode: ""

browser:
  default: firefox
  url: "http://localhost:3000"