user_id:
  automationtestuser:
    account_id: 2
  automationtestuser2:
    account_id: 22
  automationtestuser3:
    account_id: 23
  automationtestuser4:
    account_id: 24
  automationtestuser5:
    account_id: 1799
  UC6Admin:
    account_id: 1

roles:
  UCVendors:
    login: automationtestuser2@6fusion.com
    password: 7u8i&U*I
  Solution_Providers_And_UCVendors:
    login: automationtestuser3@6fusion.com
    password: 7u8i&U*I
  Admin:
    login: UC6admin@6fusion.com
    password: 1q2w!Q@W
  Solution_Providers:
    login: automationtestuser4@6fusion.com
    password: 7u8i&U*I
  Profiler:
    login: automationtestuser5@6fusion.com
    password: 7u8i&U*I

canned_data:
     iNode:  "Staging Node"
     ftp_server: "10.57.0.200"
     Template: "Automation - Full_Test_OVF"
     Template 2: "Automation - Edit_Test_OVF"
     NIC:  "VINET02"
     Meter: "Staging Node Meter"
     NIC_Field_Name: "network-name-2"
     Disk_Name: "8"
     Engine_Room_Test_NIC_Field_Name: ""
     Media_ID_1: "2"
     Media_ID_2: "1"
     Profiler_Name: ""
     Xen_Engine_Room: "Xen Engine-Room for Staging"
     iNode_ID: "1"
     NIC_ID_1: "4"
     Network_Mapping: "3"
     auth_token: "ZyuMnPZpxv8985cAADRX"
     admin_auth_token: "BbpPDjYaT53szXxEjgMe"
     VMWare_Adapter_URL: "http://adaptor-vmware.6fusion.vodka:8080"
     VMWare_Adapter_UUID: "18c62ff0-098f-0130-71ec-005056ad1d40"
     VMWare_Machine_UUID: "564d53e4-7f14-cab9-390d-ae35e2c74c73"
     Xen_Adapter_URL: "http://adaptor-xen.6fusion.vodka:8080"
     Xen_Adapter_UUID: "74de4680-f929-012f-2d48-005056ad1d40"
     Xen_Machine_UUID: "b9a42a88-2a45-dd45-bfb0-c77cf58ea277"
     Public_iNode: "VMWare 4.1"
     Private_iNode: ""

engine_room_2:
     Xen_iNode: ""
     Xen_Network_Management_Server_Interfaces: ""
     VMWare_iNode: ""

browser:
  default: firefox
  remote: "false"
  url: "https://console-staging.6fusion.com"
  alt_url: "https://console.6fusion.staging"