user_id:
  automationtestuser:
    account_id: 7
  automationtestuser2:
    account_id: 33
  automationtestuser3:
    account_id: 34
  automationtestuser4:
    account_id: 35
  UC6Admin:
    account_id: 1
roles:
  UCVendors:
    login: automationtestuser2@6fusion.com
    password: 7u8i&U*I
  Solution_Providers_And_UCVendors:
    login: automationtestuser3@6fusion.com
    password: 7u8i&U*I
  Admin:
    login: UC6admin@6fusion.com
    password: 1q2w!Q@W
  Solution_Providers:
    login: automationtestuser4@6fusion.com
    password: 7u8i&U*I
canned_data:
  iNode: "Integration Node"
  Template: "DSLinuxOVF"
  NIC: "VINET02"
  Meter: "Integration Node Meter"
  NIC_Field_Name: "network_interface_name_11"
  ISO: "DSLinux"
  Disk_Name: "media_file_38_" #must add 0 for thick, 1 for thin based on user selection.
  Engine_Room_Test_NIC_Field_Name: "network_interface_name_78"
  Media_ID_1: "22"
  Media_ID_2: "23"
  Profiler_Name: "Automation_Test_Profiler - DO NOT DELETE"
browser:
  default: 'chrome'
  url: "http://localhost:3000"
