user_id:
  automationtestuser:
    account_id: 1768
  automationtestuser2:
    account_id: 1769
  automationtestuser3:
    account_id: 1770
  automationtestuser4:
    account_id: 1771
  automationtestuser5:
    account_id: 1772
  UC6Admin:
    account_id: 1

roles:
  UCVendors:
    login: automationtestuser2@6fusion.com
    password: 7u8i&U*I
  Solution_Providers_And_UCVendors:
    login: automationtestuser3@6fusion.com
    password: 7u8i&U*I
  Admin:
    login: UC6admin@6fusion.com
    password: 1q2w!Q@W
  Solution_Providers:
    login: automationtestuser4@6fusion.com
    password: 7u8i&U*I
  Profiler:
    login: automationtestuser5@6fusion.com
    password: 7u8i&U*I

canned_data:
     ftp_server: "10.57.0.200"
     iNode:  "Automation - VMWare 4.1"
     Template: "Automation - Full_Test_Media"
     Template 2: "Automation - Edit_Test_Media"
     NIC:  "VINET02"
     Meter: "Vodka Meter"
     NIC_Field_Name: "network-name-77"
     ISO: ""
     NIC_ID_1: "77"
     Disk_Name: "9"
     Engine_Room_2_Name: "Vodka Engine Troll"
     Engine_Room_Test_NIC_Field_Name: ""
     Media_ID_1: "4"
     Media_ID_2: "5"
     Profiler_Name: ""
     Xen_Engine_Room: "Xen Engine-Room for Staging"
     iNode_ID: "3"
     Network_Mapping: "3"
     admin_auth_token: "89hL5ZWqnNSorHDMKfzy"
     auth_token: "BYVSeFDb6rT73ue8FLzg"
     VMWare_Adapter_URL: "http://adaptor-vmware.6fusion.vodka:8080"
     VMWare_Adapter_UUID: "18c62ff0-098f-0130-71ec-005056ad1d40"
     VMWare_Machine_UUID: "564d53e4-7f14-cab9-390d-ae35e2c74c73"
     Xen_Adapter_URL: "http://adaptor-xen.6fusion.vodka:8080"
     Xen_Adapter_UUID: "74de4680-f929-012f-2d48-005056ad1d40"
     Xen_Machine_UUID: "b9a42a88-2a45-dd45-bfb0-c77cf58ea277"
     Public_iNode: "VMWare 4.1"
     Private_iNode: ""


engine_room_2:
     Xen_iNode: "Xen"
     Xen_Network_Management_Server_Interfaces_id: "37"
     Xen_Network_Management_Server_Interfaces_name: "eth1"
     Xen_Network_Management_Server_Interfaces_address: "10.0.0.2/29"
     Xen_Network_Management_Server_Interfaces_public: "false"
     Xen_Network_Management_Server_Interfaces_data_center_id: "4"
     Xen_Network_Management_Server_Interfaces_service: "false"
     Xen_Designate_Service_Network_Name: "Network 1"
     VMWare_iNode: "VMware iNode for Vodka"

browser:
  default: firefox
  remote: "false"
  url: "https://console.6fusion.vodka"

graphic:
